{
 "title": "NF Traffic Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "v{{version}}" }
   ]
  },
  {
   "title": "Request Rate /sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "v{{version}}" }
   ]
  },
  {
   "title": "Server Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "up{service=\"nf-server\"}",
     "legendFormat": "v{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "uptime_seconds" }
   ]
  }
 ]
}